from db import Users
from db import Db
print("---------- db ------------------")
mydb = Db()
mydb.connect()
mydb.status()
mydb.disconnect()
mydb.status()
print("---------- users ---------------")
myusers = Users()
myusers.get_message()
print(myusers.get_usertype(username="sugar",password="sugar"))
myusers.get_message()
print(myusers.get_userid(username="rmm",password="bongbong"))
myusers.get_message()
myusers.register_user(username="xxx",password="bongbong")
myusers.get_message()
myusers.register_user(username="sugar",email="sugar@gmail.com",password="sugar")
myusers.get_message()
print(myusers.get_allusers())
print(myusers.get_user(idusers="1"))
myusers.update_user(username="rmm",newemail="bsgrmm1@gmail.com",password="bongbong")
myusers.get_message()
print(myusers.active_user(username="sugar"))
myusers.activate_user(activ=1,username="sugar")
myusers.get_message()
